version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "mongodb://mongo:27017/customURL"
      PORT: 3000
      CORS_ORIGIN_DEV: "http://127.0.0.1:5500,http://localhost:5500"
      CORS_ORIGIN_DEP: "https://customurl-9d2h.onrender.com"
      API_BASE_URL: "http://localhost:3000"
    depends_on:
      - mongo

  frontend:
    image: node:18
    working_dir: /app
    command: npx http-server ./client -p 8080 --cors
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:




# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     environment:
#        MONGO_URI: "mongodb://mongo:27017/customURL"
#        PORT: 3000
#       #  CORS_ORIGIN_DEV1: "http://127.0.0.1:5500"
#       #  CORS_ORIGIN_DEV2: "http://localhost:5500"
#        CORS_ORIGIN_DEV: "http://127.0.0.1:5500,http://localhost:5500"
#        CORS_ORIGIN_DEP: "https://customurl-9d2h.onrender.com"
#        API_BASE_URL: "http://localhost:3000"
#     depends_on:
#       - mongo

#   mongo:
#     image: mongo:latest
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo_data:/data/db

# volumes:
#   mongo_data:



# # version: '3.8'

# # services:
# #   app:
# #     build:
# #       context: .
# #       dockerfile: Dockerfile
# #     ports:
# #       - "3000:3000"
# #     environment:
# #       - PORT=3000
# #       - MONGO_URI=your_mongodb_connection_string

# #     depends_on:
# #       - mongo

# #   mongo:
# #     image: mongo:latest
# #     ports:
# #       - "27017:27017"
# #     volumes:
# #       - mongo_data:/data/db

# # volumes:
# #   mongo_data:


